# general settings
name: train_SwinFIRSSR_SSRx2_scratch
model_type: SwinFIRSSRModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: StereoSR_train
    type: StereoSRImageDataset
    dataroot_gt: datasets/StereoSR/train/StereoSR_HR_sub
    dataroot_lq: datasets/StereoSR/train/StereoSR_LR_x2_sub/
    meta_info_file: swinfir/data/meta_info/meta_info_StereoSRsubTrain_GT.txt
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_vflip: true
    use_rot: false
    use_mixup: true
    use_channelshuffle: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: StereoSR_test
    type: StereoSRImageDataset
    dataroot_gt: datasets/StereoSR/test/Flickr1024/hr
    dataroot_lq: datasets/StereoSR/test/Flickr1024/lr_x2
    meta_info_file: swinfir/data/meta_info/meta_info_Flickr1024subTest_GT.txt
    io_backend:
      type: disk


# network structures
network_g:
  type: SwinFIRSSR
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: 'SFB'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [600000, 6500000, 700000, 7500000]
    gamma: 0.5

  total_iter: 800000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLossColor
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
